### ISSUE TITLE
Export Numpy array to spice netlist

### ISSUE THREAD

**Issue by rjvallett** [ss4328/SSDK#1]
I )Component class: 
1) Capacitors
2) Resistors
3) Component to specify arbitrary voltages (A simple voltage object, sinewave, some kinda function)

II) export_np_arr = Getting a simplified numpy matrix from the master canvas grid

8/4/20

**Comment by ss4328** [comment]
What are the relevant bits of information needed in the netlist?

Basically what attributes to declare in component class?

**Comment by rjvallett** [comment]
Component: 
- Value 
- Value Suffix 
- Type(R/C/Oth)
- Neighbors

**Comment by ss4328** [comment]
Couple examples of grid to Netlist please

**Comment by rjvallett** [comment]
[testoutmatrix.txt](https://github.com/ss4328/SSDK/files/4995950/testoutmatrix.txt)
[test-transient-matrix.txt](https://github.com/ss4328/SSDK/files/4995989/test-transient-matrix.txt)
